### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by ALescoulie**
Draft of python 3 support for MDPOW. Updated core files to be compatible with python 3. Some tests still not passed due to error with Gromacs Wrapper cbook.write function. Some tests modified to find specific files.

### CODE REVIEW

**Comment by orbeckst** [comment]
@ALescoulie normal procedure is to wait for a *review* and *approval* of a PR before merging. Even if you have the power to merge, you normally wait.

**Comment by orbeckst** [comment]
This PR breaks Python 2.7. 

The GH actions is good but should have been in a separate PR for issue #158 so that we can review it separately. As a general rule: each PR should be as small as possible and address **one** issue.

**Comment by orbeckst** [comment]
I am going to just revert all these changes in develop and then we start again.

**Comment by orbeckst** [comment]
I reset develop to d28ddb42db853996a8ff5147ac65d6458e8082b5. The commits from this PR are gone now from develop but they are still in your branch (although it looks as if you did some rebasing into other commits). 

Please start new PRs.

**Comment by ALescoulie** [comment]
Sorry was trying to merge the recent changes with my branch

**Pull request merged**
