### PR TITLE
C36only

### PR DESCRIPTION
**Pull request by VOD555**
Using CHARMM36 force field instead of OPLS-AA force field.

Eventually add options to easily support other force fields (such as CHARMM/CGENFF) (Issue #87)

### CODE REVIEW

**Comment by VOD555** [comment]
clean the history and rebased

**Comment by orbeckst** [comment]
I added a better way to select the boxtype, which you could get by merging develop.

**Comment by orbeckst** [comment]
This PR is superseded by PR #103 – we might take bits and pieces from here but overall, this won't get merged in this form.

**Comment by orbeckst** [comment]
**Don't delete the branch** – we might want to cherry-pick individual commits into PR #103.

**Pull request closed without merging**
