### PR TITLE
re-enable testing of Gromacs 5

### LINKED ISSUE #36: should work with Gromacs 5.x
MDPOW should be using Gromacs 5.1.x, which is now pretty stable. GromacsWrapper recently moved to Gromacs 5.x Becksteinlab/GromacsWrapper#26 so this should work with the latest GW.

### PR DESCRIPTION
**Pull request by orbeckst**
- closes #36
- cleaned up travis.yml
- enabled mandatory testing for GMX_VERSION=5.1.2

### CODE REVIEW

**Comment by orbeckst** [comment]
The Gromacs 5.1.2 tests failed. @ianmkenney please have a look. In particular, make the assertions also show the actual exception, like
```python
try:
    do_fep_stuff()
except Exception as err:
    raise AssertionError("FEP failed with exception:\n{0}".format(str(err)))
```

Do you know why the Gromacs 5.1.2 is failing?

**Comment by ianmkenney** [comment]
I can't seem to find where gromacs is failing... `gmx grompp ...` looks okay to me. I'll keep digging

**Comment by orbeckst** [comment]
Run locally?

**Comment by orbeckst** [comment]
rebased against develop and `git push -f`.

**Comment by orbeckst** [comment]
Really weird:
* 5.1.2 passes local tests
* hangs on travis, see eg.g, https://travis-ci.org/Becksteinlab/MDPOW/jobs/175897763

@ianmkenney help!

**Comment by orbeckst** [comment]
@ianmkenney please look into using https://pypi.python.org/pypi/pytest-timeout plugin with our tests so that we can get a sense for what is happening on travis.

**Comment by orbeckst** [comment]
See https://github.com/Becksteinlab/MDPOW/issues/36#issuecomment-271901775 regarding another possibility for why Gromacs 5.x/2016 time out: wrong number of threads (as discussed the other day).

**Comment by orbeckst** [comment]
Can you have a quick look to see what needs to be done so that this branch can be merged into develop? Maybe do a rebase.

**Comment by orbeckst** [comment]
We also want to disable super-verbose test output again: just leave a comment in the travis file on what option to use (-s?) if we need it again.

**Comment by orbeckst** [comment]
I am having a quick look at this, starting with
```
git rebase develop
```

**Comment by orbeckst** [comment]
I rewrote the history and force-pushed. Waiting for ok from travis...

**Comment by orbeckst** [comment]
rebased to add proper author attribution to the rewritten commits... they are now yours again, @ianmkenney ;-)

Waiting for travis again.

**Pull request merged**
