### PR TITLE
Travis is hanging during gromacs 5 testing

### PR DESCRIPTION
**Pull request by ianmkenney**
Travis hangs on mdrun (see #65) attempting to fix outside of main branch

### CODE REVIEW

**Comment by ianmkenney** [comment]
@orbeckst Changing the `maxthreads` option in the runinput files for our two PyBOL states has fixed both gromacs 2016 and 5.1.2. It also broke 4.6.7 with a fatal error. Below I have pasted the output of Travis. Included are two FEP window `mdrun`s The first (VDW lamb=0) worked fine. The second (VDW lamb=0.5) failed with the error found at the bottom of the output. I am not seeing any reason why the second would fail and the first would not. Do you see any reason for this? 

```
DEBUG:gromacs.utilities:Working in '/tmp/tmp_zC93I/benzene/FEP/water/VDW/0000'...
gromacs.run : INFO     mdrun -cpi -stepout 2000 -deffnm md -v -nt 2 -append -nice 19
INFO:gromacs.run:mdrun -cpi -stepout 2000 -deffnm md -v -nt 2 -append -nice 19
                         :-)  G  R  O  M  A  C  S  (-:

                   Groningen Machine for Chemical Simulation

                            :-)  VERSION 4.6.7  (-:

        Contributions from Mark Abraham, Emile Apol, Rossen Apostolov, 
           Herman J.C. Berendsen, Aldert van Buuren, Pär Bjelkmar,  
     Rudi van Drunen, Anton Feenstra, Gerrit Groenhof, Christoph Junghans, 
        Peter Kasson, Carsten Kutzner, Per Larsson, Pieter Meulenhoff, 
           Teemu Murtola, Szilard Pall, Sander Pronk, Roland Schulz, 
                Michael Shirts, Alfons Sijbers, Peter Tieleman,

               Berk Hess, David van der Spoel, and Erik Lindahl.

       Copyright (c) 1991-2000, University of Groningen, The Netherlands.
         Copyright (c) 2001-2012,2013, The GROMACS development team at
        Uppsala University & The Royal Institute of Technology, Sweden.
            check out http://www.gromacs.org for more information.

         This program is free software; you can redistribute it and/or
       modify it under the terms of the GNU Lesser General Public License
        as published by the Free Software Foundation; either version 2.1
             of the License, or (at your option) any later version.

                                :-)  mdrun  (-:

Option     Filename  Type         Description
------------------------------------------------------------
  -s         md.tpr  Input        Run input file: tpr tpb tpa
  -o         md.trr  Output       Full precision trajectory: trr trj cpt
  -x         md.xtc  Output, Opt. Compressed trajectory (portable xdr format)
-cpi         md.cpt  Input, Opt!  Checkpoint file
-cpo         md.cpt  Output, Opt. Checkpoint file
  -c         md.gro  Output       Structure file: gro g96 pdb etc.
  -e         md.edr  Output       Energy file
  -g         md.log  Output       Log file
-dhdl        md.xvg  Output, Opt. xvgr/xmgr file
-field       md.xvg  Output, Opt. xvgr/xmgr file
-table       md.xvg  Input, Opt.  xvgr/xmgr file
-tabletf     md.xvg  Input, Opt.  xvgr/xmgr file
-tablep      md.xvg  Input, Opt.  xvgr/xmgr file
-tableb      md.xvg  Input, Opt.  xvgr/xmgr file
-rerun       md.xtc  Input, Opt.  Trajectory: xtc trr trj gro g96 pdb cpt
-tpi         md.xvg  Output, Opt. xvgr/xmgr file
-tpid        md.xvg  Output, Opt. xvgr/xmgr file
 -ei         md.edi  Input, Opt.  ED sampling input
 -eo         md.xvg  Output, Opt. xvgr/xmgr file
  -j         md.gct  Input, Opt.  General coupling stuff
 -jo         md.gct  Output, Opt. General coupling stuff
-ffout       md.xvg  Output, Opt. xvgr/xmgr file
-devout      md.xvg  Output, Opt. xvgr/xmgr file
-runav       md.xvg  Output, Opt. xvgr/xmgr file
 -px         md.xvg  Output, Opt. xvgr/xmgr file
 -pf         md.xvg  Output, Opt. xvgr/xmgr file
 -ro         md.xvg  Output, Opt. xvgr/xmgr file
 -ra         md.log  Output, Opt. Log file
 -rs         md.log  Output, Opt. Log file
 -rt         md.log  Output, Opt. Log file
-mtx         md.mtx  Output, Opt. Hessian matrix
 -dn         md.ndx  Output, Opt. Index file
-multidir        md  Input, Opt., Mult. Run directory
-membed      md.dat  Input, Opt.  Generic data file
 -mp         md.top  Input, Opt.  Topology file
 -mn         md.ndx  Input, Opt.  Index file

Option       Type   Value   Description
------------------------------------------------------
-[no]h       bool   no      Print help info and quit
-[no]version bool   no      Print version info and quit
-nice        int    19      Set the nicelevel
-deffnm      string md      Set the default filename for all file options
-xvg         enum   xmgrace  xvg plot formatting: xmgrace, xmgr or none
-[no]pd      bool   no      Use particle decompostion
-dd          vector 0 0 0   Domain decomposition grid, 0 is optimize
-ddorder     enum   interleave  DD node order: interleave, pp_pme or cartesian
-npme        int    -1      Number of separate nodes to be used for PME, -1
                            is guess
-nt          int    2       Total number of threads to start (0 is guess)
-ntmpi       int    0       Number of thread-MPI threads to start (0 is guess)
-ntomp       int    0       Number of OpenMP threads per MPI process/thread
                            to start (0 is guess)
-ntomp_pme   int    0       Number of OpenMP threads per MPI process/thread
                            to start (0 is -ntomp)
-pin         enum   auto    Fix threads (or processes) to specific cores:
                            auto, on or off
-pinoffset   int    0       The starting logical core number for pinning to
                            cores; used to avoid pinning threads from
                            different mdrun instances to the same core
-pinstride   int    0       Pinning distance in logical cores for threads,
                            use 0 to minimize the number of threads per
                            physical core
-gpu_id      string         List of GPU device id-s to use, specifies the
                            per-node PP rank to GPU mapping
-[no]ddcheck bool   yes     Check for all bonded interactions with DD
-rdd         real   0       The maximum distance for bonded interactions with
                            DD (nm), 0 is determine from initial coordinates
-rcon        real   0       Maximum distance for P-LINCS (nm), 0 is estimate
-dlb         enum   auto    Dynamic load balancing (with DD): auto, no or yes
-dds         real   0.8     Minimum allowed dlb scaling of the DD cell size
-gcom        int    -1      Global communication frequency
-nb          enum   auto    Calculate non-bonded interactions on: auto, cpu,
                            gpu or gpu_cpu
-[no]tunepme bool   yes     Optimize PME load between PP/PME nodes or GPU/CPU
-[no]testverlet bool   no      Test the Verlet non-bonded scheme
-[no]v       bool   yes     Be loud and noisy
-[no]compact bool   yes     Write a compact log file
-[no]seppot  bool   no      Write separate V and dVdl terms for each
                            interaction type and node to the log file(s)
-pforce      real   -1      Print all forces larger than this (kJ/mol nm)
-[no]reprod  bool   no      Try to avoid optimizations that affect binary
                            reproducibility
-cpt         real   15      Checkpoint interval (minutes)
-[no]cpnum   bool   no      Keep and number checkpoint files
-[no]append  bool   yes     Append to previous output files when continuing
                            from checkpoint instead of adding the simulation
                            part number to all file names
-nsteps      step   -2      Run this number of steps, overrides .mdp file
                            option
-maxh        real   -1      Terminate after 0.99 times this time (hours)
-multi       int    0       Do multiple simulations in parallel
-replex      int    0       Attempt replica exchange periodically with this
                            period (steps)
-nex         int    0       Number of random exchanges to carry out each
                            exchange interval (N^3 is one suggestion).  -nex
                            zero or not specified gives neighbor replica
                            exchange.
-reseed      int    -1      Seed for replica exchange, -1 is generate a seed
-[no]ionize  bool   no      Do a simulation including the effect of an X-Ray
                            bombardment on your system

No previous checkpoint file present, assuming this is a new run.
Reading file md.tpr, VERSION 4.6.7 (single precision)
Using 2 MPI threads

NOTE: The number of threads is not equal to the number of (logical) cores
      and the -pin option is set to auto: will not pin thread to cores.
      This can lead to significant performance degradation.
      Consider using -pin on (and -pinoffset in case you run multiple jobs).

starting mdrun 'Compound BNZ in water (OPLS-AA parameters)'
2500 steps,      5.0 ps.
step 0
NOTE: the minimum cell size is smaller than 1.05 times the cell size limit, will not turn on dynamic load balancing

step 2000, remaining runtime:     0 s          imb F 27% 
Writing final coordinates.
step 2500, remaining runtime:     0 s          
 Average load imbalance: 29.2 %
 Part of the total run time spent waiting due to load imbalance: 7.9 %

NOTE: 7.9 % of the available CPU time was lost due to load imbalance
      in the domain decomposition.
      You might want to use dynamic load balancing (option -dlb.)


               Core t (s)   Wall t (s)        (%)
       Time:        9.570        4.787      199.9
                 (ns/day)    (hour/ns)
Performance:       90.282        0.266

gcq#0: Thanx for Using GROMACS - Have a Nice Day

gromacs.run : INFO     MDrun completed ok, returncode = 0
INFO:gromacs.run:MDrun completed ok, returncode = 0
gromacs.run : INFO     run_check: Hooray! mdrun finished successfully
INFO:gromacs.run:run_check: Hooray! mdrun finished successfully
mdpow.run   : INFO     Running FEP (md.log) ... stand by.
INFO:mdpow.run:Running FEP (md.log) ... stand by.
mdpow.run   : INFO     Run directory: /tmp/tmp_zC93I/benzene/FEP/water/VDW/0500
INFO:mdpow.run:Run directory: /tmp/tmp_zC93I/benzene/FEP/water/VDW/0500
DEBUG:gromacs.utilities:Working in '/tmp/tmp_zC93I/benzene/FEP/water/VDW/0500'...
gromacs.run : INFO     mdrun -cpi -stepout 2000 -deffnm md -v -nt 2 -append -nice 19
INFO:gromacs.run:mdrun -cpi -stepout 2000 -deffnm md -v -nt 2 -append -nice 19
                         :-)  G  R  O  M  A  C  S  (-:

                   Groningen Machine for Chemical Simulation

                            :-)  VERSION 4.6.7  (-:

        Contributions from Mark Abraham, Emile Apol, Rossen Apostolov, 
           Herman J.C. Berendsen, Aldert van Buuren, Pär Bjelkmar,  
     Rudi van Drunen, Anton Feenstra, Gerrit Groenhof, Christoph Junghans, 
        Peter Kasson, Carsten Kutzner, Per Larsson, Pieter Meulenhoff, 
           Teemu Murtola, Szilard Pall, Sander Pronk, Roland Schulz, 
                Michael Shirts, Alfons Sijbers, Peter Tieleman,

               Berk Hess, David van der Spoel, and Erik Lindahl.

       Copyright (c) 1991-2000, University of Groningen, The Netherlands.
         Copyright (c) 2001-2012,2013, The GROMACS development team at
        Uppsala University & The Royal Institute of Technology, Sweden.
            check out http://www.gromacs.org for more information.

         This program is free software; you can redistribute it and/or
       modify it under the terms of the GNU Lesser General Public License
        as published by the Free Software Foundation; either version 2.1
             of the License, or (at your option) any later version.

                                :-)  mdrun  (-:

Option     Filename  Type         Description
------------------------------------------------------------
  -s         md.tpr  Input        Run input file: tpr tpb tpa
  -o         md.trr  Output       Full precision trajectory: trr trj cpt
  -x         md.xtc  Output, Opt. Compressed trajectory (portable xdr format)
-cpi         md.cpt  Input, Opt!  Checkpoint file
-cpo         md.cpt  Output, Opt. Checkpoint file
  -c         md.gro  Output       Structure file: gro g96 pdb etc.
  -e         md.edr  Output       Energy file
  -g         md.log  Output       Log file
-dhdl        md.xvg  Output, Opt. xvgr/xmgr file
-field       md.xvg  Output, Opt. xvgr/xmgr file
-table       md.xvg  Input, Opt.  xvgr/xmgr file
-tabletf     md.xvg  Input, Opt.  xvgr/xmgr file
-tablep      md.xvg  Input, Opt.  xvgr/xmgr file
-tableb      md.xvg  Input, Opt.  xvgr/xmgr file
-rerun       md.xtc  Input, Opt.  Trajectory: xtc trr trj gro g96 pdb cpt
-tpi         md.xvg  Output, Opt. xvgr/xmgr file
-tpid        md.xvg  Output, Opt. xvgr/xmgr file
 -ei         md.edi  Input, Opt.  ED sampling input
 -eo         md.xvg  Output, Opt. xvgr/xmgr file
  -j         md.gct  Input, Opt.  General coupling stuff
 -jo         md.gct  Output, Opt. General coupling stuff
-ffout       md.xvg  Output, Opt. xvgr/xmgr file
-devout      md.xvg  Output, Opt. xvgr/xmgr file
-runav       md.xvg  Output, Opt. xvgr/xmgr file
 -px         md.xvg  Output, Opt. xvgr/xmgr file
 -pf         md.xvg  Output, Opt. xvgr/xmgr file
 -ro         md.xvg  Output, Opt. xvgr/xmgr file
 -ra         md.log  Output, Opt. Log file
 -rs         md.log  Output, Opt. Log file
 -rt         md.log  Output, Opt. Log file
-mtx         md.mtx  Output, Opt. Hessian matrix
 -dn         md.ndx  Output, Opt. Index file
-multidir        md  Input, Opt., Mult. Run directory
-membed      md.dat  Input, Opt.  Generic data file
 -mp         md.top  Input, Opt.  Topology file
 -mn         md.ndx  Input, Opt.  Index file

Option       Type   Value   Description
------------------------------------------------------
-[no]h       bool   no      Print help info and quit
-[no]version bool   no      Print version info and quit
-nice        int    19      Set the nicelevel
-deffnm      string md      Set the default filename for all file options
-xvg         enum   xmgrace  xvg plot formatting: xmgrace, xmgr or none
-[no]pd      bool   no      Use particle decompostion
-dd          vector 0 0 0   Domain decomposition grid, 0 is optimize
-ddorder     enum   interleave  DD node order: interleave, pp_pme or cartesian
-npme        int    -1      Number of separate nodes to be used for PME, -1
                            is guess
-nt          int    2       Total number of threads to start (0 is guess)
-ntmpi       int    0       Number of thread-MPI threads to start (0 is guess)
-ntomp       int    0       Number of OpenMP threads per MPI process/thread
                            to start (0 is guess)
-ntomp_pme   int    0       Number of OpenMP threads per MPI process/thread
                            to start (0 is -ntomp)
-pin         enum   auto    Fix threads (or processes) to specific cores:
                            auto, on or off
-pinoffset   int    0       The starting logical core number for pinning to
                            cores; used to avoid pinning threads from
                            different mdrun instances to the same core
-pinstride   int    0       Pinning distance in logical cores for threads,
                            use 0 to minimize the number of threads per
                            physical core
-gpu_id      string         List of GPU device id-s to use, specifies the
                            per-node PP rank to GPU mapping
-[no]ddcheck bool   yes     Check for all bonded interactions with DD
-rdd         real   0       The maximum distance for bonded interactions with
                            DD (nm), 0 is determine from initial coordinates
-rcon        real   0       Maximum distance for P-LINCS (nm), 0 is estimate
-dlb         enum   auto    Dynamic load balancing (with DD): auto, no or yes
-dds         real   0.8     Minimum allowed dlb scaling of the DD cell size
-gcom        int    -1      Global communication frequency
-nb          enum   auto    Calculate non-bonded interactions on: auto, cpu,
                            gpu or gpu_cpu
-[no]tunepme bool   yes     Optimize PME load between PP/PME nodes or GPU/CPU
-[no]testverlet bool   no      Test the Verlet non-bonded scheme
-[no]v       bool   yes     Be loud and noisy
-[no]compact bool   yes     Write a compact log file
-[no]seppot  bool   no      Write separate V and dVdl terms for each
                            interaction type and node to the log file(s)
-pforce      real   -1      Print all forces larger than this (kJ/mol nm)
-[no]reprod  bool   no      Try to avoid optimizations that affect binary
                            reproducibility
-cpt         real   15      Checkpoint interval (minutes)
-[no]cpnum   bool   no      Keep and number checkpoint files
-[no]append  bool   yes     Append to previous output files when continuing
                            from checkpoint instead of adding the simulation
                            part number to all file names
-nsteps      step   -2      Run this number of steps, overrides .mdp file
                            option
-maxh        real   -1      Terminate after 0.99 times this time (hours)
-multi       int    0       Do multiple simulations in parallel
-replex      int    0       Attempt replica exchange periodically with this
                            period (steps)
-nex         int    0       Number of random exchanges to carry out each
                            exchange interval (N^3 is one suggestion).  -nex
                            zero or not specified gives neighbor replica
                            exchange.
-reseed      int    -1      Seed for replica exchange, -1 is generate a seed
-[no]ionize  bool   no      Do a simulation including the effect of an X-Ray
                            bombardment on your system

No previous checkpoint file present, assuming this is a new run.
Reading file md.tpr, VERSION 4.6.7 (single precision)
Using 2 MPI threads

NOTE: The number of threads is not equal to the number of (logical) cores
      and the -pin option is set to auto: will not pin thread to cores.
      This can lead to significant performance degradation.
      Consider using -pin on (and -pinoffset in case you run multiple jobs).

starting mdrun 'Compound BNZ in water (OPLS-AA parameters)'
2500 steps,      5.0 ps.
step 0
NOTE: the minimum cell size is smaller than 1.05 times the cell size limit, will not turn on dynamic load balancing


-------------------------------------------------------
Program mdrun, VERSION 4.6.7
Source code file: /tmp/gromacs_build/source/gromacs-4.6.7/src/mdlib/domdec.c, line: 3245

Fatal error:
The box size in direction X (2.449397) times the triclinic skew factor (0.816496) is too small for a cut-off of 1.000000 with 2 domain decomposition cells, use 1 or more than 2 processors or increase the box size in this direction
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
```

**Comment by orbeckst** [comment]
Gromacs tells you what to do:

>  use 1 or more than 2 processors 

Try `maxthreads = 3` and `maxthreads = 1`. No idea why this is not triggered in 5.x and 2016 – maybe it got smarter in the domdec.

**Comment by orbeckst** [comment]
P.S.: HOORAY for having 5.x/2016 passing all tests. Awesome.

**Comment by orbeckst** [comment]
Please ping me once this passes. I am *so* looking forward to merging it. I will probably squash everything together on merge unless you tell me that these should remain separate commits.

**Comment by orbeckst** [comment]
[3 threads](https://travis-ci.org/Becksteinlab/MDPOW/builds/195920818) takes a little bit longer than [2 threads]()

| GMX            | 2 threads | 3 threads     |
|------------|------------|-------------|
| 4.6.7           | 2:50           | 3:23     |
| 5.1.2            | 5:14            | 6:38 |
| 2016           | 4:44           | 5:26 |  

(GMX 4.6.7 at 2 threads fails but the others pass at 2 and 3 threads.)

Can you please also try `maxthreads=1` and add the numbers ?

**Comment by ianmkenney** [comment]
@orbeckst See updated table

**Comment by orbeckst** [comment]
I changed it to 3 threads and rebased.

**Pull request merged**
