### PR TITLE
Fix oct topology molecule name

### LINKED ISSUE #154: "No such group" during solvation step with octanol
I'm trying to run 
<source>mdpow-equilibrium --solvent octanol glyh101.yml</source>
I did the same with <source>--solvent water</source> and had no issues.

I copied the runinput.yml from the templates and made a few changes (copied here as .txt).
[glyh101.txt](https://github.com/Becksteinlab/MDPOW/files/6736989/glyh101.txt)

Here are the structure (step4.1_equilibration.gro) and topology (Glyh101.ipt) input files (copied here as .txt).
[Glyh101.txt](https://github.com/Becksteinlab/MDPOW/files/6736996/Glyh101.txt)
[step4.1_equilibration.txt](https://github.com/Becksteinlab/MDPOW/files/6736998/step4.1_equilibration.txt)

I got the following error
<source>
GROMACS:      gmx genion, version 2021.1
Executable:   /nfs/homes/rsexton/Library/miniconda3/envs/glyh101/bin/gmx
Data prefix:  /nfs/homes/rsexton/Library/miniconda3/envs/glyh101
Working dir:  /nfs/homes/rsexton/Projects/CFTR/glyh101/mdpow/glyh101/Equilibrium/octanol/solvation
Command line:
  gmx genion -nn 0 -o ionized.gro -p /nfs/homes/rsexton/Projects/CFTR/glyh101/mdpow/glyh101/Equilibrium/octanol/top/system.top -s topol.tpr -pname NA -np 1 -nname CL

Reading file topol.tpr, VERSION 2021.1 (single precision)
Reading file topol.tpr, VERSION 2021.1 (single precision)
Will try to add 1 NA ions and 0 CL ions.
Select a continuous group of solvent molecules
Group     0 (         System) has  7468 elements
Group     1 (          Other) has  7468 elements
Group     2 (            GYH) has    43 elements
Group     3 (           OcOH) has  7425 elements
Select a group: Error: No such group 'SOL'
Select a group: 
-------------------------------------------------------
Program:     gmx genion, version 2021.1
Source file: src/gromacs/topology/index.cpp (line 902)

Fatal error:
Cannot read from input

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/bin/mdpow-equilibrium", line 62, in <module>
    S = equilibrium_simulation(cfg, opts.solvent, dirname=opts.dirname)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/mdpow/run.py", line 227, in equilibrium_simulation
    maxwarn=maxwarn)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/mdpow/equil.py", line 394, in solvate
    params = self._setup_solvate(**kwargs)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/mdpow/equil.py", line 348, in _setup_solvate
    return gromacs.setup.solvate(**kwargs)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/gromacs/setup.py", line 626, in solvate
    **kwargs)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/gromacs/setup.py", line 492, in solvate_ion
    input=solvent_name)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/gromacs/core.py", line 398, in __call__
    return self.run(*args, **kwargs)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/gromacs/core.py", line 178, in run
    results, p = self._run_command(*_args, **_kwargs)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/gromacs/core.py", line 611, in _run_command
    self.check_failure(result, command_string=p.command_string)
  File "/nfs/homes/rsexton/Library/miniconda3/envs/mdpow/lib/python2.7/site-packages/gromacs/core.py", line 566, in check_failure
    raise GromacsError(rc, msg)
gromacs.exceptions.GromacsError: [Errno 1] Gromacs tool failed
Command invocation: printf "SOL\n" | gmx genion -nn 0 -o ionized.gro -p /nfs/homes/rsexton/Projects/CFTR/glyh101/mdpow/glyh101/Equilibrium/octanol/top/system.top -s topol.tpr -pname NA -np 1 -nname CL
</source>

### PR DESCRIPTION
**Pull request by VOD555**
Fix #154 
In `itp` files for dry octanol, the molecule name in `atom` section doesn't match the one in `molecule` section.
So, here, we replace OcOH with SOL to match the molecule names.

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
Why did this work in the past? Did we use custom top files??

Can you add tests, please? We probably only need to run grompp, something like the first stage of the equilibrium workflow.

**Comment by VOD555** [comment]
@orbeckst It only raised the error when gromacs wanted to replace some solvent molecules to add ions, which would recognize the molecule name from the `atom` section in `tip` files while the molecule name in `gro` or `top` files were based on the name defined in `molecule` section. 

When dealing with neutral molecules (SAMPL), it wouldn't need to replace solvent molecules, so no error was raised. But when the molecule has charge, such as Rick's, the error is raised. 

To test this we need a charged molecule. Maybe I add a sodium ion system for the tests?

**Review by orbeckst — CHANGES_REQUESTED** [review]
There are various issues related to ions #97 #85 and in the docs I said that charged molecules are currently no supported. Let's not start with ions right here, at least not as a test case for a FEP calculation.

For a test it then you could add a test that builds an octanol system (using [`Goct.solvate()`](https://mdpow.readthedocs.io/en/latest/equil.html#mdpow.equil.Simulation.solvate) etc) _with options to add 4 Na and 4 Cl_ — we don't have to run the system, just checking that it generates it and that it contains the right number of ions afterwards.

Please also update CHANGES.

**Comment by orbeckst** [comment]
Great that you added the tests. The octanol-ion ones fail for most GROMACS versions, though. The output is not very informative, though, so I have no idea what's going wrong.

**Comment by VOD555** [comment]
I'm going to run a local test starting with gromacs wrapper's solvate function.

**Comment by VOD555** [comment]
@orbeckst I think the problem is due to that `gromacswrapper` currently doesn't support np, and nn (number of negative and positive ions) input as well as using the concentration with a non-water solvent.

Here's the source code of `gromacswrapper` setup.py from line 451. We can see in the `if concentration` part, the selection inputs for generating an index file is only for water molecule.

```
    with in_dir(dirname):
        with open('none.mdp','w') as mdp:
            mdp.write('; empty mdp file\ninclude = {include!s}\nrcoulomb = 1\nrvdw = 1\nrlist = 1\n'.format(**mdp_kwargs))
        qtotgmx = cbook.grompp_qtot(f='none.mdp', o='topol.tpr', c=structure,
                                    p=topology, stdout=False, maxwarn=grompp_maxwarn)
        qtot = round(qtotgmx)
        logger.info("[{dirname!s}] After solvation: total charge qtot = {qtotgmx!r} = {qtot!r}".format(**vars()))

        if concentration != 0:
            logger.info("[{dirname!s}] Adding ions for c = {concentration:f} M...".format(**vars()))
            # target concentration of free ions c ==>
            #    N = N_water * c/c_water
            # add ions for concentration to the counter ions (counter ions are less free)
            #
            # get number of waters (count OW ... works for SPC*, TIP*P water models)
            rc,output,junk = gromacs.make_ndx(f='topol.tpr', o='ow.ndx',
                                              input=('keep 0', 'del 0', 'a OW*', 'name 0 OW', '', 'q'),
                                              stdout=False)
            groups = cbook.parse_ndxlist(output)
            gdict = {g['name']: g for g in groups}   # overkill...
            N_water = gdict['OW']['natoms']                  # ... but dict lookup is nice
            N_ions = int(N_water * concentration/CONC_WATER) # number of monovalents
        else:
            N_ions = 0
```

**Comment by orbeckst** [comment]
That makes sense. The concentration calculation wouldn't make any sense with non-water solvents. However, I am not even sure that the GW code works with _all_ water models – do they all actually call the oxygen OW??

Does your change still work with the mixed solvent? https://github.com/Becksteinlab/MDPOW/blob/43485ddef51ed7df8cda4ac9cb8332b3dbe14ed9/mdpow/equil.py#L637-L649 seems to say that the mixed-solvent code expects OcOH. 

This issues looks as if it's tangled up with how to deal with ions properly. My understanding is that it does not limit the current functionality, right? Therefore, we can push this to a later milestone.

**Comment by VOD555** [comment]
I think the current version of groamcs wrapper's solvate function with concentration input only works with some specific water models. For the test itself, we need a update for gromcas wrapper to support np, nn inputs, and we don't need to think about ion concentration in octanol.

It still works with met octanol. In the topology files of mixed octanol, water molecules were named as `SOL` which is the atomtype selected for being replaced with ions, and octanol was defined as OcOH``.

**Comment by orbeckst** [comment]
Can you please raise an issue for GW solvate to support nn/np and mention this PR, so that we don't forget? Thanks!

**Comment by orbeckst** [comment]
@VOD555 is this a PR we should get finished for a 0.8.0 release?

**Comment by VOD555** [comment]
@orbeckst It's not necessary for normal use of MDPOW (for neutral molecules), so I think it can be finished after 0.8.0. And we still need a gromacswrapper supports nn and np input.

**Pull request closed without merging**
