### PR TITLE
Set up multiple versions of gromacs for travisCI

### PR DESCRIPTION
**Pull request by ianmkenney**
Installing and running tests for two different versions of Gromacs (5.1.x and 4.6.6)

### CODE REVIEW

**Comment by ianmkenney** [comment]
@orbeckst do we need `sudo: false` in `.travis.yml`? I think it is needed to install from the ubuntu repos. Otherwise I get permission denied.

**Comment by orbeckst** [comment]
> On 30 May, 2016, at 15:35, Ian Kenney <notifications@github.com> wrote:
> 
> @orbeckst do we need sudo: false in .travis.yml? I think it is needed to install from the ubuntu repos. Otherwise I get permission denied.

Hm, I see.

The advantage of `sudo = False` is that we then run on the Travis container based infrastructure (ie docker images). Typically throughput and performance is better on them so it’s good to do when we can do it.

However, try out sudo = True and see you can get it to work. In the midterm we’ll just build our own Gromacs condo packages and then we can go back to docker containers.

**Comment by orbeckst** [comment]
Pssoibly useful travis docs:
- [Build Matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix)
- [environment variables](https://docs.travis-ci.com/user/environment-variables/)

**Comment by orbeckst** [comment]
The travis docs on [Installing Packages on Container-based Infrastructure](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure) show how we can use the container based infrastructure (`sudo = False`) *if we only need standard packages*. Now that Gromacs is installable from condas we should be able to revert back to container-based.

@ianmkenney can you look at this once the condas-Gromacs works on the `sudo=True`?

**Comment by orbeckst** [comment]
This looks encouraging. 

Many tests fail because a test is trying to copy files and makes assumptions about the current working directory. Use [Resource Etraction](http://setuptools.readthedocs.io/en/latest/pkg_resources.html#resource-extraction) (part of [pkg_resources](http://setuptools.readthedocs.io/en/latest/pkg_resources.html)) to properly set paths in the tests, e.g., using `resource_filename(__file__, name)`.

**Comment by orbeckst** [comment]
See how we do it in [MDAnalysisTests.datafiles](https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/datafiles.py) (and also make sure that the datafiles are installed in setup.py – see MDA for example). Basically
```python
	from pkg_resources import resource_filename
	PSF = resource_filename(__name__, 'data/adk.psf')
```
and then use
```python
	from .datafiles import PSF
```
to use the PSF files.

**Pull request merged**
